### ISSUE TITLE
error html in middle and doble html in end

### ISSUE THREAD

**Issue by albertobraschi** [olegkoval/magento2-regenerate_url_rewrites#10]
Hello.
I used the extension and it worked very well.
a single problem happened. added a .html in the middle of the url and .html.html at the end.
can you help me?

url-store.com/saude-e-beauty/perfumes-and-fragrances.html/perfumes/femininos/perfume-feminino-ck-one-shock-edt-200ml-calvin-klein.html.html

**Comment by olegkoval** [comment]
Hello Albert.

This extension do not generate a URL keys. It start a built-in mechanism of re-generating a URL Rewrites **based** on URL keys.

Please, check 2 things:
1) in admin panel open this product ("perfume feminino ck one shock edt 200ml calvin klein") and check what URL key it have. If URL key contain at the end ".html.html" then please check your customization of URL key generating code (or if you use custom extensions for this - then this extension code or settings).

2) if URL key of this product is OK and it looks like `perfume-feminino-ck-one-shock-edt-200ml-calvin-klein.html` or `perfume-feminino-ck-one-shock-edt-200ml-calvin-klein`
then you should check templates code - how URLs are built on frontend. For me it's looks like in template some custom code just concatenate full category URL + product URL key + '.html'.

Best regards,
Oleg Koval
