### ISSUE TITLE
Which version is compatible with magento 2.1?

### ISSUE THREAD

**Issue by LucScu** [olegkoval/magento2-regenerate_url_rewrites#103]
Hi,
i installed last version 1.4.3 on m2.1.2 but it not works, it doesn't find `Magento\CatalogUrlRewrite\Model\UrlRewriteBunchReplacer`.
Is there a working version for m2.1?

thx

**Comment by olegkoval** [comment]
Hi @LucScu 

Please, check your Magento 2.1 installation, because Magento 2.1 have this Model:
https://github.com/magento/magento2/blob/2.1/app/code/Magento/CatalogUrlRewrite/Model/UrlRewriteBunchReplacer.php

This file should be in `vendor/magento/module-catalog-url-rewrite/Model` folder.

**Comment by LucScu** [comment]
Hi @olegkoval,
thx for reply, but here
https://github.com/magento/magento2/tree/2.1.2/app/code/Magento/CatalogUrlRewrite/Model
no Magento\CatalogUrlRewrite\Model\UrlRewriteBunchReplacer class

**Comment by LucScu** [comment]
HI @olegkoval ,
you linked me a branch that is not the 2.1.2 tag release.
Please check here
https://github.com/magento/magento2/tree/2.1.2/app/code/Magento/CatalogUrlRewrite/Model
you see that there isn't `Magento\CatalogUrlRewrite\Model\UrlRewriteBunchReplacer`

**Comment by olegkoval** [comment]
Hi @LucScu 

Now it's compatible with this version: from [v1.5.2](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.5.2) extension not use this Magento model.

Best regards,
Oleg Koval

**Comment by LucScu** [comment]
Thx, very good!
