### ISSUE TITLE
Category Regenerate Use Case

### ISSUE THREAD

**Issue by snoroozi** [olegkoval/magento2-regenerate_url_rewrites#104]
What is the use case for regenerating categories? What problem do people face when they need this? Is it speed of category loading? 

Also, if you regenerate category url rewrites, will that remove custom redirect entries as well for really old redirects where key has changed in the past?  I don't want to lose that traffic.

**Comment by hostep** [comment]
There are known bugs in Magento which can screw up the url rewrites for categories, for example by moving them around in the hierarchy: https://github.com/magento/magento2/issues/16202

As to your other question: be very careful with this module here, I did some elaborate testing and sometimes it changes things you don't want to change.
I can strongly recommend dumping the following database tables before and after you run this tool, and then do a comparison to see how and what it changes exactly:
- `url_rewrite`
- `catalog_category_entity_varchar`
- `catalog_product_entity_varchar`

And please don't execute this module directly on a production environment without testing!

**Comment by olegkoval** [comment]
Closed because it's a Magento issue.
