### ISSUE TITLE
Keep URL's results in redirect loop

### ISSUE THREAD

**Issue by evs-xsarus** [olegkoval/magento2-regenerate_url_rewrites#108]
As it turns out, when keeping the old URL's, a redirect loop is the result. The cause is that the the type for the 301-redirect must be set to 'custom' and not 'product'.

Can this be fixed?

NB I've only tested this with the product URL regeneration.

**Comment by olegkoval** [comment]
Hello @evs-xsarus 

Fixed in v1.5.x - please upgrade to latest version.

Best regards,
Oleg Koval
