### ISSUE TITLE
can this extension work with another plugin?

### ISSUE THREAD

**Issue by hongxy** [olegkoval/magento2-regenerate_url_rewrites#115]
I try to remove Parent-Category-from-Child-Category-URL, so that I found this magento plugin. https://github.com/tahiriqbalnajam/Magento2-Remove-Parent-Category-from-Child-Category-URL

but it seems to me that this regenerator does NOT take the "remove parent category" into consideration. Is there anyway to make these 2 extensions work together?

Thanks!

**Comment by olegkoval** [comment]
Hello @hongxy 

What problem you want to solve? You want to remove from product Url a category path?

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Hello @hongxy 

As we discussed: now you can use Models of this extension via DI. Please, upgrade to version 1.5.2.

Best regards,
Oleg Koval
