### ISSUE TITLE
URL's are not updating in backend & frontend

### ISSUE THREAD

**Issue by startshopNL** [olegkoval/magento2-regenerate_url_rewrites#117]
Please see below, the task is running but nothing updating in backend & frontend. All other caches are flushed (Varnish, Redis)

php bin/magento ok:urlrewrites:regenerate --entity-type=product --product-id=3637
Regenerating of URL rewrites:

----------------------------------------------------
Please, support me on:
https://www.patreon.com/olegkoval
----------------------------------------------------

[Store ID: 0, Store View code: admin]:
[>                                                                      ] 0%  0/[=======================================================================] 100%  1/1

[Store ID: 1, Store View code: en]:
[>                                                                      ] 0%  0/[=======================================================================] 100%  1/1

Reindexation... Done
Cache refreshing... Done
If you use some external cache mechanisms (e.g.: Redis, Varnish, etc.) - please, refresh this external cache.

----------------------------------------------------
Please, support me on:
https://www.patreon.com/olegkoval
----------------------------------------------------

Finished

**Comment by olegkoval** [comment]
Hello @startshopNL 

I've fixed this issue in version 1.5.0. Please upgrade extension and regenerate Url Rewrites.

Best regards,
Oleg Koval
