### ISSUE TITLE
PHP7.3 Compatability

### ISSUE THREAD

**Issue by jaimiedijstra** [olegkoval/magento2-regenerate_url_rewrites#118]
I get the following error during an ssh install when trying to install with PHP7.3:

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your                        PHP version (7.3.13) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your                        PHP version (7.3.13) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your                        PHP version (7.3.13) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer (locked at v2.13.3, req                       uired as ~2.13.0) -> satisfiable by friendsofphp/php-cs-fixer[v2.13.3].

Installation failed, reverting ./composer.json to its original content.
`

Do you have plans to make it compatible?

**Comment by olegkoval** [comment]
Hello @jaimiedijstra 

The issue is in requirements of extension "friendsofphp/php-cs-fixer" not in Url Rewrites.. Please, try to update "friendsofphp/php-cs-fixer".

Best regards,
Oleg Koval
