### ISSUE TITLE
Category/Product

### ISSUE THREAD

**Issue by picarda** [olegkoval/magento2-regenerate_url_rewrites#119]
Hello,
Is it possible to make this?
mydomain.com/category/product.html

Thank you.

**Comment by olegkoval** [comment]
Hello @picarda 

You already have it "out of the box" in version 1.5.0:
1) please, install  1.5.0 version of extension (or l);
2) then in Magento store configuration set option "Use Categories Path for Product URLs" to "Yes" (Configuration -> Catalog -> Catalog -> Search Engine Optimization ->  Use Categories Path for Product URLs);
3) Save configuration changes. Flush/Clean cache.
4) run command (without any params):
`php bin/magento ok:urlrewrites:regenerate`
5) Enjoy.

Extension use a built-in API to generate a Url Rewrites and Url Rewrites depends to this config option.

Best regards,
Oleg Koval
