### ISSUE TITLE
Regenerate url_keys and update rewrites

### ISSUE THREAD

**Issue by codedge** [olegkoval/magento2-regenerate_url_rewrites#120]
Hey.

I've got some hundreds of products that have a wrong product `url_key`. The customer just copied one product again and again and did not update the url key.

**Example**
* towel-style-buckingham-3214
* towel-style-buckingham-3221
* towel-style-buckingham-3124
* .. and so on

I'd like to remove the existing url_key, generate a new one based on the product name and then update the url rewrite.

Is that something I can do with the extension? Currently it just used the old url key to generate rewrites which, in this case, does not help much.

Thanks!

**Comment by olegkoval** [comment]
Hello @codedge 

Yes, this extension re-generate Url Rewrites based on name (but also you can use a option to use a current url_key values to re-generate Url Rewrites). And, please, use the latest version 1.5.0.

Best regards,
Oleg Koval

**Comment by codedge** [comment]
I see, but this is not what I intend. I'd like to replace the wrong `url_key` with the one generated from product name and then, based on this new key, generate a rewrite for it.

Hope you do understand what I want 😄 

So then the product should be available via this new URL key, and not via the old anymore.

**Comment by olegkoval** [comment]
Hi @codedge 

Yes, it's clear to me. If you will use version 1.5.0 and you will run:
`$> php bin/magento ok:urlrewrites:regenerate`

Then extension will re-generate new "url_key" for products based on the name value and then will re-generate Url Rewrites based on new "url_key" values.

Best regards,
Oleg Koval

**Comment by codedge** [comment]
Yes, that is what I run. `php bin/magento ok:url:regenerate —product-id=1234`. The thing is, that the url key is still the same when I check in Magento admin.

So regardless if I run that for one or all products. The url keys stay the same.

I run Magento 2.3.4 and the latest version 1.5.0 of the extension.

**Comment by olegkoval** [comment]
Do you have a test instance of your Magento installation?

**Comment by codedge** [comment]
Yes, I can provide a testing system. I'll send the credentials to your gmail address.

**Comment by olegkoval** [comment]
@codedge Yes, it would be great. Thank you.

**Comment by codedge** [comment]
@olegkoval Just to check: Did you receive my mail? Let me know if you need more.

Thanks im advance!

**Comment by olegkoval** [comment]
Hi @codedge 
Yes, just checked "Spam" and email from you was there. Good that you mentioned about this here.

Can you add here (or in another email) the list of products which have the issue name vs url_key (url rewrites)? It will save me the time.

**Comment by codedge** [comment]
Sure, I'll send you another mail.

**Comment by codedge** [comment]
Sent the mail a minute ago.

**Comment by olegkoval** [comment]
@codedge Thank you. Got it.

**Comment by olegkoval** [comment]
@codedge Thank you for the test server. I've released a quick fix (version 1.5.1) and updated extension on your test server via composer.
Tested and looks like it works like you expected.

Please, re-test and confirm.

**Comment by codedge** [comment]
Hui... that looks great! 🎉 Awesome, the now the URLs are exactly like I wanted!

Thanks a lot Oleg!
