### ISSUE TITLE
Regenerate url_keys for categories

### ISSUE THREAD

**Issue by codedge** [olegkoval/magento2-regenerate_url_rewrites#121]
Hi Oleg,

I experience the same issue that existed for products #120 but now for categories.  
When I run `ok:... --category-id=244` the url_key is just taken without properly updating it based on the category name.

I suspect this needs to be fixed in [RegenerateCategoryRewrites](https://github.com/olegkoval/magento2-regenerate_url_rewrites/blob/master/Model/RegenerateCategoryRewrites.php#L205)?

**Comment by olegkoval** [comment]
Hi @codedge 

Fixed this in version 1.5.2. Please update extension.
