### ISSUE TITLE
Specifying --category-id uses wrong entity

### ISSUE THREAD

**Issue by codedge** [olegkoval/magento2-regenerate_url_rewrites#122]
When specifying `--category-id=123` only it seems to still use `product` as `entity_type`. Only when I explicitly set `--entity-type=category` it runs correctly.

**Does not work**
`php bin/magento ok:urlrewrites:regenerate --category-id=244 // Does nothing`

**Works**
`php bin/magento ok:urlrewrites:regenerate --entity-type=category --category-id=244 // Works, regenerate for category 244`

I think when only specifying `--category-id` it is clear that the entity `category` should be used.

**Comment by olegkoval** [comment]
Hi @codedge 

Added this feature in version 1.5.2. Please update extension.
