### ISSUE TITLE
Version 1.5.6 was not created in packagist

### ISSUE THREAD

**Issue by hws47a** [olegkoval/magento2-regenerate_url_rewrites#128]
It happened because of the redundand "version"  in the composer.json file.
The version should be either updated either removed. I would consider removing it to simplify the flow (I see there were already a few issues like this one).
After that version 1.5.6 can be added to packagist by removing the tag and re-creating it.

**Comment by olegkoval** [comment]
Hello Vladimir.

Thank you for this report. Fixed.

Best regards,
Oleg Koval
