### ISSUE TITLE
Commands not changing the urls in Magento 2.3.4

### ISSUE THREAD

**Issue by Subjekt2Change** [olegkoval/magento2-regenerate_url_rewrites#129]
**Describe the bug**
Both of the following commands are not working:
php bin/magento ok:urlrewrites:regenerate --entity-type=product --product-id=30271
php bin/magento ok:urlrewrites:regenerate --entity-type=category --category-id=774

On a local test system both commands worked marvelous, however on the live server they seem to work, but after finishing the urls are still the same as before. No errors are thrown. Is there some sort of debug mode?

Magento Version: 2.3.4
I am using the latest module version.
There are no additional caches active, apart from the magento cache.
I am inexperienced with Magento, so i apologize should there be a simple solution for this problem.

**Expected behavior**
After executing the commands the product / category should have updated urls.

Product ID=30271 "Tästprodukt" should have the new url "shop/taest/taestprodukt", but keeps its old url "shop/tast/tastprodukt"

Category ID=774 "Täst" should have the new url "shop/taest", but it keeps the old url "shop/tast".

Both are redirecting to their old urls.

**Comment by olegkoval** [comment]
Hi @Subjekt2Change 

Magento use a transliteration to create a URL slug, so why "Tästprodukt" should be translated into "taestprodukt" instead of "tastprodukt"?

If you want to use the custom transliteration then you need to customize (override) method which transliterate test into slug.

**Comment by Subjekt2Change** [comment]
Hi @olegkoval 

I am sorry, it seems i have misunderstood your module. So i have to first override the default method that creates the url slugs and then run your module again.

I got confused because it worked from scratch on my local VM and expected the same behavior on the server.

Thank you for your support and your quick answer! I am closing this ticket.
