### ISSUE TITLE
Extra "/" at request_path for Product URL

### ISSUE THREAD

**Issue by datasiantech** [olegkoval/magento2-regenerate_url_rewrites#13]
hi Oleg,
Thanks for creating and sharing the extension.
We have been using the extension, trying to regenerate URL after mass Product Import, but we get a mixed of request path value, Product has an extra "/" as prefix for the request_path, Category is fine.

Can you please help
![image](https://user-images.githubusercontent.com/11314414/39035379-f536a6ec-44a3-11e8-93e1-f28fd17e0607.png)

**Comment by olegkoval** [comment]
Hi.

Please check this setting - maybe you've added slash at the end:
![image](https://user-images.githubusercontent.com/254432/39956636-ebe5b8ec-55e4-11e8-91d6-2754fdfc6ebd.png)

Best regards,
Oleg Koval

**Comment by tuyennn** [comment]
Using 1.3.0
This problem still persistent with categories

![image](https://user-images.githubusercontent.com/4010395/47839078-fd319580-dde3-11e8-843d-c97576cd4138.png)

**Comment by olegkoval** [comment]
Hello @tuyennn 
Please, upgrade to v1.3.1 (added a fix for leading slashes in request path generated by Magento core model) and empty url keys.
