### ISSUE TITLE
Error Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.29.

### ISSUE THREAD

**Issue by mohammedTBB** [olegkoval/magento2-regenerate_url_rewrites#159]
**Describe the bug**
Magento 2.4.4
php 8.1
olegkoval/magento2-regenerate-url-rewrites 1.6.0

An error is showing when regenrating url key:
Reindexation...Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.29.
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.29. in /var/www/clients/client1/web37/web/magento/vendor/composer/platform_check.php on line 24
 Done

**Expected behavior**
No error

**To Reproduce**
execute regenerate command without option "--no-regen-url-key"
Ex: php bin/magento ok:urlrewrites:regenerate --entity-type=category --store-id=4 --category-id=300

**Screenshots**
![image](https://user-images.githubusercontent.com/66772877/189099770-b3cab2f2-373f-41a4-a699-5f8b4c925a3c.png)

**Comment by jg-development** [comment]
I think you are not running on php 8.1, but php 7.4 obviously.
what is the output of "php -v"?

imho this can be closed
