### ISSUE TITLE
libpng warning

### ISSUE THREAD

**Issue by kauansoft** [olegkoval/magento2-regenerate_url_rewrites#16]
[root@mail public_html]# bin/magento ok:urlrewrites:regenerate
Regenerating of URL rewrites:

[Store ID: 0, Store View code: admin]:
....................
....................
....................
....................
........
[Store ID: 1, Store View code: default]:
....................
....................
....................
....................
........

Reindexation...
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image

**Comment by olegkoval** [comment]
Hello.

This is the bug of library libpng: https://sourceforge.net/p/libpng/bugs/165/

Please ask your system admin to update the library.

Best regards,
Oleg Koval
