### ISSUE TITLE
OlegKoval\RegenerateUrlRewrites\Console\Command\RegenerateUrlRewrites::execute() must be of the type int, "null" returned

### ISSUE THREAD

**Issue by josseve** [olegkoval/magento2-regenerate_url_rewrites#165]
Magento 2.4.6, PHP 8.2
After end process of bin/magento ok:urlrewrites:regenerate

There is an error in /.../vendor/symfony/console/Command/Command.php at line: 301
Return value of "OlegKoval\RegenerateUrlRewrites\Console\Command\RegenerateUrlRewrites::execute()" must be of the type int, "null" returned.#0

**Comment by Nurgiel** [comment]
as per: vendor/symfony/console/Command/Command.php
protected function execute @return int 0 if everything went fine, or an exit code

so to fix this error we just need to add return 0; at the end of execute() function in vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewrites.php

Patch:
`diff --git a/vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewrites.php b/vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewrites.php
index bba265efa..f95b13420 100644
--- a/vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewrites.php
+++ b/vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewrites.php
@@ -115,7 +115,7 @@ class RegenerateUrlRewrites extends RegenerateUrlRewritesAbstract
      * Regenerate Url Rewrites
      * @param  InputInterface  $input
      * @param  OutputInterface $output
-     * @return void
+     * @return int 0 if everything went fine, or an exit code
      */
     protected function execute(InputInterface $input, OutputInterface $output)
     {
@@ -166,6 +166,8 @@ class RegenerateUrlRewrites extends RegenerateUrlRewritesAbstract
 
         $this->_showSupportMe();
         $this->_output->writeln('Finished');
+
+        return 0;
     }
 
     /**
`

**Comment by Nurgiel** [comment]
I've made a PR for this issue:
https://github.com/olegkoval/magento2-regenerate_url_rewrites/pull/167

**Comment by chrisastley** [comment]
> Can you please add this issue in your latest update of Master Branch? We really need this

Add the commit as a patch using cweagans/composer-patches

https://github.com/olegkoval/magento2-regenerate_url_rewrites/commit/cb541ccfadca1aa200275e531d77c17fe30124d0.patch

**Comment by olegkoval** [comment]
Issue was fixed in release v1.6.1.

Thank you All for the bug reporting.
