### ISSUE TITLE
Undefined constant Symfony\Component\Console\Command\Command::SUCCESS

### ISSUE THREAD

**Issue by RalphVB** [olegkoval/magento2-regenerate_url_rewrites#169]
**Describe the bug**
At the end of the command execution, it always thrown the error "Undefined constant Symfony\Component\Console\Command\Command::SUCCESS".

**Expected behavior**
Finishing the execution of the command without errors.

**To Reproduce**
Whenever I run "bin/magento ok:urlrewrites:regenerate --entity-type=category" or "bin/magento ok:urlrewrites:regenerate --entity-type=product" commands, at the end of the execution throws the error "Undefined constant Symfony\Component\Console\Command\Command::SUCCESS".

**Screenshots**
![image](https://github.com/olegkoval/magento2-regenerate_url_rewrites/assets/11371957/903da434-6be3-45aa-b03f-b1643fd3db8f)

**Additional context**
I noticed this bug and wanted to let you know about it. Regards,

**Comment by lucatiberia** [comment]
Hi, I'm also having the same problem even though the command seems to work

**Comment by adammix** [comment]
Hi, I'm having same problem.
Cheers

**Comment by nmarquev** [comment]
same here !

**Comment by olegkoval** [comment]
Issue was fixed in release v1.6.2.

Than you All for the bug reporting.
