### ISSUE TITLE
Unique constraint violation found

### ISSUE THREAD

**Issue by rgilchrist** [olegkoval/magento2-regenerate_url_rewrites#17]
Hi 
When I run the command on my Magento 2.2.4 installation, I get a lot of '.', but I also get a number of 

'Unique constraint violation found'

Can you tell me what is causing this?

Cheers
Rob

**Comment by olegkoval** [comment]
Hi.

This is the Magento 2.2.4 issue - please check for updates/fixes this issues reports:
https://github.com/magento/magento2/issues/13055
https://github.com/magento/magento2/issues/13224

Best regards,
Oleg Koval
