### ISSUE TITLE
seo friendly url will not be used after regeneration

### ISSUE THREAD

**Issue by glwstor** [olegkoval/magento2-regenerate_url_rewrites#18]
We are using a multi store view shop with version 2.2.3.
All products has set a seo friendly url, but magento shows a lot of them only with catalog/product/view/id...
After regenerating urls with your extension, the urls are still the same. We see the ugly urls after generation of sitemaps. <loc>https://www.xxxxxxxxx.de/catalog/product/view/id/473</loc>

Even if we made an update of the url at the product detail page, the url will still be the same.
The only way to set a new url is to select the checkbox at the product page to "store view german" -> "use default value" ->save to activate the rewrite. After this it is possible to change the url in proper way.

Is it possible to adjust your extension, that if force the creation of a rewirte like the "use default value"?

**Comment by olegkoval** [comment]
Hi.

Thank you for message.
Do you have a test store? And can we use email to discuss this?
My email: oleh.koval@gmail.com

Best regards,
Oleg Koval

**Comment by magento2pl** [comment]
I think the problem is with duplicated url keys. The best will be:
1. get all child categories from root category of store
2. foreach through those categories ( not all store category )

Now the problem is when there are more root categories and multistores and in other root categories are categories with same url key.

**Comment by Bmacuser1** [comment]
We just installed it todaz with Magento 2.2.4 and Multistore with 2 websites and 2 domain.

Thats from our developer:

1) I have truncate Url_ rewrite table data.
2) I have installed the olegkoval/magento2-regenerate_url_rewrites plugin.
3) bin/magento setup:upgrade and bin/magento setup:static-content:deploy command.
4) Then regenerate all the URLs using this command bin/magento ok:urlrewrites:regenerate
5) Then I have to see the category URLs same as before nothing to changed the URLs on the test site.

We have installed it on our testsite

**Comment by magento2pl** [comment]
The problem occurs when You have multistores with different root categories and same urls in different root category. I make a change like I wrote before and it is working correct with multistores.

**Comment by Sil-B** [comment]
@magento2pl do you have the change available? I also have problems with duplicate urls in my multistore.

**Comment by olegkoval** [comment]
Hello.

Issue was fixed (multistore with same categories tree) in version [1.3.0](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.3.0). Please upgrade and test.

Best regards,
Oleg Koval
