### ISSUE TITLE
Doubling Up On .html Extensions

### ISSUE THREAD

**Issue by C0D31GN1T3R** [olegkoval/magento2-regenerate_url_rewrites#19]
I've been organizing my store for a while moving products and categories around, so there were a tonne of redirects and duplicate URL's.  I found your module and decided to rewrite the entire catalog of URL's, you module works great for the most part but I have a tonne of `some-category.html/someproduct.html` type URL's now.  Not a big issue I can just run a script to remove any .html's in the middle of the URL's but thought I would mention it incase it was a simple fix.

**Comment by mjoraid** [comment]
I noticed `some-category.html/someproduct.html` a while ago but didn't' give it attention.  I did a lot of stuff since then.  I do not notice it now. Maybe because I disable .html extension from Magento Admin Panel (for other reasons)  or because I updated from Mag 2.2.2 to 2.2.5.
