### ISSUE TITLE
language switcher stopped working

### ISSUE THREAD

**Issue by LouNik1984** [olegkoval/magento2-regenerate_url_rewrites#20]
Hi, 
I have a magento 2.2.2 version and when I added a second store view for english language, the urls broke from www.domain.com/product-url.html to domain.com/catalog/category/view/s/t-shirt/id/439/. I installed this extension and run the command bin/magento ok:urlrewrites:regenerate as per instruction. The command worked beautifully and all the urls are now correct on both store views. 

However, I have also the language switcher enabled on my website and after I run the command the language switcher stopped working. What I mean by "stopped working" is that: 
- the switcher is correctly shown on frontend
- if I click on it I can open the dropdown with the second language
- BUT if I click on the second language I should go to mydomain.com/second-store-code/something.html istead I'm stil on mydomain.com/first-store-code/something.html. 

The switcher was working before running and if I manually write the store code in the url and click enter, then I can go to the correct url. 

Any idea on how can I fix this?

Thanks

**Comment by LouNik1984** [comment]
I dug a little and it looks like another bug of magento 2.2, not related to this extension. Basically, the switcher stops working if you add the store code to urls. The issue is here: https://github.com/magento/magento2/issues/11963, there as well is a patch to fix the issue (https://github.com/klimart/magento2-patches/blob/master/patches/11963-language-issue.patch). I tried and it works, so we may consider this issue solved

**Comment by olegkoval** [comment]
@LouNik1984 Thank you for researching.
