### ISSUE TITLE
Invalid URL key

### ISSUE THREAD

**Issue by akfarko** [olegkoval/magento2-regenerate_url_rewrites#24]
Hello, I'm trying to  use your extention, while my product url looks like this:
https://DOMAIN.com/catalog/product/view/id/[id]/s/[url_key]/

Product were imported via bulk import.

I ran:
bin/magento ok:urlrewrites:regenerate 1
and
bin/magento ok:urlrewrites:regenerate 1 --save-old-urls

but i get always this error:

[Store ID: 1, Store View code: default]:
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
..............Invalid URL key

Can you please help me, how to fix it? Thank you.

**Comment by olegkoval** [comment]
Hell @akfarko.

Please, update extension to the version 1.1.0 and confirm that issue still exists.

Best regards,
Oleg Koval.

**Comment by olegkoval** [comment]
Hi @akfarko 
Please upgrade extension to the latest version. And confirm if issue still exists.

**Comment by olegkoval** [comment]
Issue was fixed.
