### ISSUE TITLE
Not Deleting Old URL's

### ISSUE THREAD

**Issue by THORDUDE** [olegkoval/magento2-regenerate_url_rewrites#25]
The process works fine however looking in dashboard all previous URL's are still there. Am I missing something?

**Comment by olegkoval** [comment]
Hello.

Did you used a key " --save-old-urls"?

**Comment by THORDUDE** [comment]
No just php bin/magento ok:urlrewrites:regenerate 1

Shane Warta, Creative Director
_______________________________________________________________________________
Ocelco, Inc l 1111 Industrial Park Road l Brainerd MN l 56401
P: (800)328.5343 x2468  l  F: (866)829.9744  l  E: swarta@ocelco.com<mailto:swarta@ocelco.com> l  W: www.ocelcoinc.com<http://www.ocelcoinc.com>

**Comment by olegkoval** [comment]
Do you have a multiple stores in this magento instance or only one?

**Comment by THORDUDE** [comment]
Just a single store

Shane Warta, Creative Director
_______________________________________________________________________________
Ocelco, Inc l 1111 Industrial Park Road l Brainerd MN l 56401
P: (800)328.5343 x2468  l  F: (866)829.9744  l  E: swarta@ocelco.com<mailto:swarta@ocelco.com> l  W: www.ocelcoinc.com<http://www.ocelcoinc.com>

**Comment by THORDUDE** [comment]
2.2.3
No test site just live
https://www.curtaintracking.com

**Comment by olegkoval** [comment]
Ok, thanks.
Can you, please, add here, in comment, a couple of old url rewrites (which was not removed) and new URL rewrites for same objects (products or categories)?

**Comment by THORDUDE** [comment]
https://www.curtaintracking.com/36x84-sure-chek-shower-curtain.html	Page current
https://www.curtaintracking.com/36-wide-sure-chek/36x84-sure-chek-shower-curtain.html	Page in list as well as current.

**Comment by olegkoval** [comment]
This is not "old" URL rewrite - it's URL rewrite for the link to the product in category. If you assigned product to some category then Magento will generate this URL rewrite. So, both URL rewrites are valid and first URL rewrite is a direct link to the product and second URL rewrite is a link to the product in category and this URL rewrite was re-generated after removing all current URL rewrites.

If you will remove this product from "36-wide-sure-chek" category and re-generate URL rewrites then a second URL rewrite ("36-wide-sure-chek/36x84-sure-chek-shower-curtain.html") will not exists.
