### ISSUE TITLE
update shell -h information

### ISSUE THREAD

**Issue by simonrl** [olegkoval/magento2-regenerate_url_rewrites#26]
First of all thanks for this module.

`bin/magento ok:urlrewrites:regenerate -h` misses some of the options that are explained in the Readme. They should be added.

If that's ok for you, I will be happy to provide a pull request with updated help explanations.

**Comment by olegkoval** [comment]
Hello.

Yes, please.

**Comment by olegkoval** [comment]
Merged & closed.
