### ISSUE TITLE
Area code already set

### ISSUE THREAD

**Issue by raivisdejus** [olegkoval/magento2-regenerate_url_rewrites#3]
Hi,

I had issue with 
https://github.com/olegkoval/magento2-regenerate_url_rewrites/blob/4ab3ad16eb8c01fb684d8687198221e0a736d451/Console/Command/RegenerateUrlRewrites.php#L111

When running the `bin/magento ok:urlrewrites:regenerate` I got error `[Magento\Framework\Exception\LocalizedException]  
  Area code is already set `

**Comment by olegkoval** [comment]
Hello Raivis.

Thank you for issue submitting.
I've fixed this issue and made a release of v1.0.3 with this fix.

Best regards,
Oleg Koval
