### ISSUE TITLE
Category URLs generated for store ids where category is not used

### ISSUE THREAD

**Issue by danielpfarmer** [olegkoval/magento2-regenerate_url_rewrites#30]
Hey,

This is the scenario:

We have 2 websites / 2 stores

Website 1 / store 1 uses one category structure / root category, while website 2 / store 2 uses another.

The problem is that when generating urls for store 2, the module generates the urls for all categories under both root categories for store 2. It should only generate the urls for categories under to the root category assigned to the store.

This is causing conflicts if there are categories with the same url key under different root categories. 

- root category 1 (website 1)
- - chairs (chairs)
- - desks (desks)
- root category 2 (website 2)
- - chairs (chairs) <------ this would cause a conflict with the categories in store 1 even though they are under completely different root categories
- - office desks (office-desks)

Hope this makes sense 🤞

**Comment by olegkoval** [comment]
Hello @danielpfarmer 

Issue fixed. Please upgrade to latest version.
