### ISSUE TITLE
Compatibility to Magento Commerce 2.2.5

### ISSUE THREAD

**Issue by avstudnitz** [olegkoval/magento2-regenerate_url_rewrites#31]
Currently the module is not fully compatible to Magento Commerce. If we are installing Magento with this module installed (i.e. during integration tests), we get the following error:
```
Starting Magento installation:
File permissions check...
[Progress: 1 / 721]
Required extensions check...
[Progress: 2 / 721]
Enabling Maintenance Mode...
[Progress: 3 / 721]
Installing deployment configuration...
[Progress: 4 / 721]
Installing database schema:

                                                                                                        
  [Zend_Db_Statement_Exception]                                                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xyz.flag' doesn't exist, query was: SELECT `flag`.* FROM `flag` WHERE (`flag`.`flag_code`='staging')  
```

After I removed the module, it worked.

My assumption is that it could be because there is no `sequence` tag in the `module.xml`, the module should probably run after the `Magento_UrlRewrite` module.

**Comment by avstudnitz** [comment]
Well, for me it was... clearly reproducable, and I reinstalled Magento from an empty database about 20 times, until I found that this extension was causing the error. After that, I reinstalled twice with and twice without this extension to be absolutely sure. Note it's the Commerce edition, not OpenSource.

**Comment by olegkoval** [comment]
Hello @avstudnitz.

Yes, sorry. The issue was on extension side. I've fixed issue and released a new version "1.2.0".
Please, update and use this latest version.

Best regards,
Oleg Koval.

**Comment by avstudnitz** [comment]
Great, thanks a lot!

**Comment by olegkoval** [comment]
@avstudnitz Please, upgrade to v1.2.1 - I've fixed compilation issues.

**Comment by ashvinimarwal** [comment]
This worked for me on Adobe commerce 2.3
 php bin/magento setup:uninstall
rm -rf var/cache/ var/di/ var/page_cache/  generated/  pub/static/
php bin/magento setup:install --cleanup-database ...other options...
