### ISSUE TITLE
Issue with Magento 2.2.6

### ISSUE THREAD

**Issue by ctadlock** [olegkoval/magento2-regenerate_url_rewrites#35]
This error occurs when trying to enable this extension via the command line when using Magento 2.2.6.

Possibly related to https://github.com/olegkoval/magento2-regenerate_url_rewrites/issues/32?

```PHP Fatal error:  Declaration of Magento\CatalogUrlRewrite\Observer\UrlRewriteHandler\Proxy::generateProductUrlRewrites(Magento\Catalog\Model\Category $category) must be compatible with Magento\CatalogUrlRewrite\Observer\UrlRewriteHandler::generateProductUrlRewrites(Magento\Catalog\Model\Category $category): array in generated/code/Magento/CatalogUrlRewrite/Observer/UrlRewriteHandler/Proxy.php on line 7```

**Comment by ctadlock** [comment]
This is an issue with Magento: https://github.com/magento/magento2/pull/17768

**Comment by mageho** [comment]
Same here on Magento 2.2.6

**Comment by olegkoval** [comment]
@ctadlock , @mageho Thank you for your help with this issue.
Closed.
