### ISSUE TITLE
compile fails for 1.2

### ISSUE THREAD

**Issue by ebgreen** [olegkoval/magento2-regenerate_url_rewrites#36]
upgraded to 1.2

bin/magento setup:di:compile
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 60.0 MiB
                                                                                                 
  [RuntimeException]                                                                             
  Source class "\CategoryCollection" for "CategoryCollectionFactory" generation does not exist.  
                                                                                                 
1.1.1 works fine

**Comment by olegkoval** [comment]
Hello @ebgreen .

Thank you for report. I've fixed compilation issue in v1.2.1. 

Best regards,
Oleg Koval

**Comment by ebgreen** [comment]
no problem

Thanks,


Eric Green

CTO

Cell: (619) 985 - 1270

Email: <admin@pitbullaudio.com>admin@pitbullaudio.com
<eric@expresslyweb.com>
