### ISSUE TITLE
Stile the same url rewrite issues

### ISSUE THREAD

**Issue by koopjesboom** [olegkoval/magento2-regenerate_url_rewrites#37]
**catalog/product/view/id/3042/s/**maisto-mercedes-benz-clk-gtr-d2-11-1997-grijs-1-18/

Fighting this issues for years now.
Any solution would be nice.

Thanks for the effort to write this tool.

**Comment by olegkoval** [comment]
Hello @koopjesboom 

Do you have some test server or sandbox where I can debug this issue?

Best regards,
Oleg Koval

**Comment by koopjesboom** [comment]
Best,

 

No we don’t have a test environment for our sites.

 

I have repaired some of these products on our front-page by hand.

I have changed these products manually.

But as far as I can see a lot of products of onwstock.eu have this problem

 

The problem is  a double // for example: https://ownstock.eu <https://ownstock.eu/lithografie-e-kuhn-mercedes-benz-w196-silberpfeil-stirling-moss-8-grijs> //lithografie-e-kuhn-mercedes-benz-w196-silberpfeil-stirling-moss-8-grijs”

 

If I look at my URL rewrites of Ownstock.eu these URLs have a / at the beginning.

If I remove this / the URL is working fine after I renew the caches.

 



 

 

 

 



 

I hope you understand this problem. If the forward / is removed from all URL’s our problem is solved.

But I should also not save new products with this forward / 

 

Thank you for the help I hope I can donate you on PayPal somehow.

 

Ik hoop u hiermee voldoende te hebben geïnformeerd met een vriendelijke groet bram Slagboom.

I hope I informed you well enough, best regards Bram Slagboom.

 

Adres/Address

Koopjesboom V.O.F.

Lorentzweg 26

2964LN Groot-Ammers

 

Tel/Phone : 0031184634329

Mobile : 0031651180371

E-Mail : info@koopjesboom.com

 

 <https://kbmodelcars.com/> https://kbmodelcars.com

 <https://ownstock.eu/> https://ownstock.eu

 

KVK : 58220259

 

Van: Oleg Koval <notifications@github.com> 
Verzonden: maandag 29 oktober 2018 23:04
Aan: olegkoval/magento2-regenerate_url_rewrites <magento2-regenerate_url_rewrites@noreply.github.com>
CC: koopjesboom <info@koopjesboom.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [olegkoval/magento2-regenerate_url_rewrites] Stile the same url rewrite issues (#37)

 

Hello @koopjesboom <https://github.com/koopjesboom> 

Do you have some test server or sandbox where I can debug this issue?

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Hi @koopjesboom 

"Double slash" issue was fixed in latest version v1.3.1. Please upgrade extension and regenerate url rewrites.
