### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function setStoreId()

### ISSUE THREAD

**Issue by senders** [olegkoval/magento2-regenerate_url_rewrites#39]
Hello,

since version 1.2.0 I am getting the following error in magento 2.1.15

Regenerating of URL rewrites:

[Store ID: 0, Store View code: admin]:

Fatal error: Uncaught Error: Call to a member function setStoreId() on null in ../html/vendor/olegkoval/magento2-regenerate-url-rewrites/Console/Command/RegenerateUrlRewritesAbstract.php:383

Version 1.1.1 ist working fine.

**Comment by olegkoval** [comment]
Hello @senders .

This issue was fixed in the release v1.2.2. Please update extension.

Best regards,
Oleg Koval
