### ISSUE TITLE
No patch versions on packagist.org

### ISSUE THREAD

**Issue by andkirby** [olegkoval/magento2-regenerate_url_rewrites#4]
Hi Oleg!

It's good to find your module and solve Magento issue. Just in time. :)

I see you have some patch versions. They are not presented on packagist.org.
Do you keep it in private? Or you just haven't set up webhooks for packagist.org?

Thanks!

**Comment by olegkoval** [comment]
Hello Kirby.

Thank you. Yes, I haven't set up a webhooks. Now it's fixed.

Best regards,
Oleg Koval

**Comment by andkirby** [comment]
Thanks!
