### ISSUE TITLE
magento 2.2.6 has error in the vendor/module-catalog

### ISSUE THREAD

**Issue by redouanhajjari** [olegkoval/magento2-regenerate_url_rewrites#40]
When i use urlrewrites:regenerate i will get this error.

URL key for specified store already exists. Product ID: 3196. Request path: *****
..PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() must be of the type string, null given, called in /home/****/domains/****/public_html/shop/vendor/magento/module-catalog/Model/ProductRepository.php on line 675 and defined in /home/****/domains/****/public_html/shop/vendor/magento/module-catalog/Model/ProductRepository.php:685

**Comment by olegkoval** [comment]
Hello @redouanhajjari , @celocore 

Please, upgrade extension to version [1.3.0](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.3.0) and check if issue still exists.

Best regards,
Oleg Koval

**Comment by jlfguthrie** [comment]
I am getting the same error on v 2.2.6 with 1.3.0

..PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() 
must be of the type string, null given, called in /usr/www/users/animaeswjw/vendor/magento/module-catalog/Model/Pro
ductRepository.php on line 675 and defined in /usr/www/users/animaeswjw/vendor/magento/module-catalog/Model/Product
Repository.php:685
Stack trace:
#0 /usr/www/users/animaeswjw/vendor/magento/module-catalog/Model/ProductRepository.php(675): Magento\Catalog\Model\
ProductRepository->prepareSku(NULL)
#1 /usr/www/users/animaeswjw/vendor/magento/module-catalog/Model/ProductRepository.php(308): Magento\Catalog\Model\
ProductRepository->saveProductInLocalCache(Object(Magento\Catalog\Model\Product\Interceptor), 'adf0bb68589672e...')
#2 /usr/www/users/animaeswjw/vendor/magento/module-catalog/Model/ProductRepository.php(273): Magento\Catalog\Model\
ProductRepository->cacheProduct('adf0bb68589672e...', Object(Magento\Catalog\Model\Product\Interceptor))
#3 /usr/www/users/animaeswjw/vendor/magento/module-catalog-url-re in /usr/www/users/animaeswjw/vendor/magento/modul
e-catalog/Model/ProductRepository.php on line 685

**Comment by jlfguthrie** [comment]
> I am getting the same error on v 2.2.6 with 1.3.0

I have a multi store setup of 10 stores.
The largest has 33000 products. The rest have less.
It is failing on only the 3 largest stores.
The other stores complete successfully.

**Comment by jlfguthrie** [comment]
> > I am getting the same error on v 2.2.6 with 1.3.0
> 
> I have a multi store setup of 10 stores.
> The largest has 33000 products. The rest have less.
> It is failing on only the 3 largest stores.
> The other stores complete successfully.

OK, I managed to solve this.
The issue occurs when products do not have an SKU. The SKU field is blank.
If you try delete the product in Magento it throws out a similar error.
I used a 3rd party tool to delete the affected products (6 out of 33000).
After flushing cache and indexing I ran it again and it worked!

**Comment by olegkoval** [comment]
Thank you for researching. Closed.
