### ISSUE TITLE
Product urls doesnt work because it has // in the url

### ISSUE THREAD

**Issue by redouanhajjari** [olegkoval/magento2-regenerate_url_rewrites#41]
when i urlrewrites:regenerate, my urls will get //
example: http://****/shop//****.html when i go to the url i get an 404 error.
Im using magento 2.2.6 and it has an subfolder.

**Comment by clementhadrot** [comment]
Same problem !

**Comment by olegkoval** [comment]
Hello @redouanhajjari , @clementhadrot 

Please, upgrade extension to version [1.3.0](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.3.0) and check if issue in your store still exists.

Best regards,
Oleg Koval

**Comment by tuyennn** [comment]
#13

**Comment by olegkoval** [comment]
Hello @redouanhajjari , @clementhadrot , @tuyennn  
Please, upgrade to v1.3.1 (added a fix for leading slashes in request path generated by Magento core model) and empty url keys.

**Comment by tuyennn** [comment]
@olegkoval Nice update, I could confirm it has no double / on latest v1.3.1

**Comment by olegkoval** [comment]
Fixed. Closed.
