### ISSUE TITLE
Product url keys

### ISSUE THREAD

**Issue by Userr017** [olegkoval/magento2-regenerate_url_rewrites#52]
I have two stores and all product url keys is lost after command bin/magento ok:urlrewrites:regenerate. So it doesn't save url keys to any product.

Tested also commands and doesn't work: bin/magento ok:urlrewrites:regenerate --no-clean-url-key and bin/magento ok:urlrewrites:regenerate --save-old-urls

![empty](https://user-images.githubusercontent.com/26794034/47750929-285b9e00-dc99-11e8-8f51-da3ea4ce919c.JPG)

**Comment by burtflaxton** [comment]
You need to update to 1.3.

bin/magento ok:urlrewrites:regenerate --no-clean-url-key

**Comment by Userr017** [comment]
I have latest version 1.3.0 and Magento 2.2.6 but it is after command every products url keys empty.

**Comment by burtflaxton** [comment]
Are you running multistore? Are your URLs different per store/website? Maybe try running the store code within the command like below. Replace the 2 for store id you need to regen.

bin/magento ok:urlrewrites:regenerate 2 --no-clean-url-key

**Comment by Userr017** [comment]
All commands tested and same issue. This empty url keys issue is only with products.

**Comment by Userr017** [comment]
Anything idea how bulk save all products so i get back all url keys?

**Comment by hyquality** [comment]
i'm having the same issue.

**Comment by olegkoval** [comment]
Fixed issue in v1.3.1. Please update extension and regenerate URL rewrites - URL keys will be back.

Please, confirm a fix.

**Comment by sheky87** [comment]
I can confirm. It's working now.

**Comment by olegkoval** [comment]
Fixed. Closed.
