### ISSUE TITLE
Category url keys

### ISSUE THREAD

**Issue by Userr017** [olegkoval/magento2-regenerate_url_rewrites#55]
I have issue with categories url keys because it create English store the same url keys what is the Finnish store.
All this extension commands is tested and same issue.

![command](https://user-images.githubusercontent.com/26794034/47881163-047d9100-de2e-11e8-90e3-a006e3225517.JPG)

Magento 2.2.6 and this extension version 1.3.0.

**Comment by Userr017** [comment]
Anything idea how bulk save all products so i get back all url keys?

**Comment by Userr017** [comment]
Still same issue with version 1.3.1.

**Comment by Userr017** [comment]
Please fix this issue soon as possible?

**Comment by olegkoval** [comment]
Hello @Userr017 

I've released v1.4.0. Please, test it and confirm that issue still exists or not.

Best regards,
Oleg Koval

**Comment by Userr017** [comment]
Still same issue. 

I tried also remove database tables where all generated url keys but after this some products and categories without real url keys and some with wrong url keys.
DELETE FROM url_rewrite WHERE entity_type='product';
DELETE FROM url_rewrite WHERE entity_type='category';

**Comment by olegkoval** [comment]
Hello @Userr017 .

Do you have some test server/sandbox where I can debug this issue? Because on my test stores everything works Ok.

P.S. Also I've released v1.4.1.

Best regards,
Oleg Koval.

**Comment by sajidunnar** [comment]
@olegkoval   Thanks for building awesome utility

**Comment by olegkoval** [comment]
@sajidunnar Thank you. You are welcome!

**Comment by Userr017** [comment]
I installed latest version and now all works. Thanks so much!

**Comment by olegkoval** [comment]
@Userr017 You are welcome!

**Comment by rshcherbinin** [comment]
Hi Oleg!
I have the same issue in version 1.4.3.
Category collection loads default values.
And we have the same URL keys for categories in different stores.

I'd suggest to add $categoriesCollection->setStore($storeId) in _getCategoriesCollection function
