### ISSUE TITLE
URL rewrites are deleted before regenerating

### ISSUE THREAD

**Issue by schmengler** [olegkoval/magento2-regenerate_url_rewrites#56]
When regenerating the URL rewrites for a store, first all entries in `url_rewrite` for that store are deleted. This should be optional, to keep existing URLs working during regeneration.

**Comment by burtflaxton** [comment]
You need to be running.

`bin/magento ok:urlrewrites:regenerate --no-clean-url-key`

**Comment by olegkoval** [comment]
Are you need additional option for this?
Then what the difference should be between "--save-old-urls" option and this new?

**Comment by olegkoval** [comment]
Hello @schmengler 

Now you have 2 options:
"--no-clean-url-key" - to not update/regenerate (based on name) a product URL key(s)
"--save-old-urls" - to not remove a old URL rewrites
