### ISSUE TITLE
Table  url_rewrite get wrong request_path

### ISSUE THREAD

**Issue by zperovsek** [olegkoval/magento2-regenerate_url_rewrites#59]
Hi,

I have magento with multiple stores. All store use same root Category. When I regenerate urls for one store (for example storeID = 2), I get values (request_path) from default store (storeID = 0).

Magento ver. 2.2.5
Plugin ver. 1.3.1

**Comment by olegkoval** [comment]
Hello @zperovsek 

I've released v1.4.0. Please, test it and confirm that issue still exists or not.

Best regards,
Oleg Koval

**Comment by petterjv** [comment]
I have the same issue and I think I have a solution, will crate a PR

**Comment by olegkoval** [comment]
Fixed in v1.4.2.
