### ISSUE TITLE
1.3.1 Incredibly Slow

### ISSUE THREAD

**Issue by jlfguthrie** [olegkoval/magento2-regenerate_url_rewrites#60]
Upgraded to 1.3.1 and it is incredibly slow.

The previous version 1.3.0 it took about 30 minutes to complete (35000 products). On 1.3.1 it takes in excess of 3 hours, and in fact I have not waited for it to complete as I killed the process, downgraded and went back to 1.3.0.

It took about 30 minutes for the first progress dot to appear and each subsequent progress dot.

**Comment by jbutkowski** [comment]
I'm experiencing the same issue. I have 43,000 products and it took over 36 hours to complete. No idea why though.

**Comment by BNEP** [comment]
same here, over 27000 products. works endless. Is running now about 20 hours :-(

**Comment by jbutkowski** [comment]
Downgrading to version 1.3.0 solved the problem for me.  😄

**Comment by budoland-ab** [comment]
Notice. Do not downgrade to 1.3.0 while using Magento 2.2.6.

The regenerator is quite fast then but deletes all url_keys from products and that results in pain.

**Comment by Kamik** [comment]
The DELETE SQL query in the catalog_url_rewrite_product_category table is too slow (because ON DELETE CASCADE). We have 1.4 million products and and 3 stores and a DELETE query takes 20 to 25 seconds ....  and  will never finish.

**Comment by Kamik** [comment]
https://github.com/magento/magento2/issues/11951

**Comment by olegkoval** [comment]
Hello All.

I'm working now on version 1.4 and I plan to release it on this weekend.
In this version I did rewrote of the whole extension logic.

Please take  a patience - I did celebrated a Christmas and New Year and have a family. So, I can't spend whole free time just for a Magento :)

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Hello All.

I've released version 1.4.0. Please, test it. Take into account that logic of whole script was changed a bit - read "How To" section.

**Comment by olegkoval** [comment]
Hello @jlfguthrie , @jbutkowski , @BNEP , @budoland-ab , @paul-blundell .

Issue was fixed in version 1.4.1. Please, upgrade extension.

Best regards,
Oleg Koval.
