### ISSUE TITLE
Memory limit error?

### ISSUE THREAD

**Issue by teoteo** [olegkoval/magento2-regenerate_url_rewrites#61]
I’ve installed the module using composer on Magento 2.2.6 store but I get this error

```
$ bin/magento ok:urlrewrites:regenerate
Regenerating of URL rewrites:

----------------------------------------------------
Please, support me on:
https://www.patreon.com/olegkoval
https://api.fondy.eu/s/ghYyR
----------------------------------------------------


[Store ID: 0, Store View code: admin]:

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```
but I’ve assigned 12G and the store has about 8000 products.
```
$ php -i | grep memory
memory_limit => 12G => 12G
Collecting memory statistics => No
```

if I check PHP error log I get:

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1048576 bytes) in /MY_STORE_PATH/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 58`

How can I run it?

**Comment by olegkoval** [comment]
Hello @teoteo 

Please, test a new version of extension (1.4.x).

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Closed.
