### ISSUE TITLE
Did not regenerate rewrites at all

### ISSUE THREAD

**Issue by ywsw** [olegkoval/magento2-regenerate_url_rewrites#62]
I am using a fresh install of 2.2.6 and I have just run the extension (php bin/magento ok:urlrewrites:regenerate) which did not show any issues while running in the console. However, it did not actually generate any URL rewrites at all (it did, however, delete all of my previous url rewrites). 

What am I doing wrong?

**Comment by twistedatrocity** [comment]
Same here on 2.1.16 ...  ALL products now have /product/view/id/etc now on front end url, which is what I was trying to fix to begin with... now the entire store is this way. Fortunately I did this on a test server and not production.

**Comment by olegkoval** [comment]
Hello @ywsw , @budoland-ab , @twistedatrocity 

I've released v1.4.0. Please test it and confirm that issue is fixed (extension pass my internal tests).

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Closed.
