### ISSUE TITLE
Url rewrite not created for products; only product category rewrites created

### ISSUE THREAD

**Issue by ctadlock** [olegkoval/magento2-regenerate_url_rewrites#63]
If a product is not in a category, then when `magento ok:urlrewrites:regenerate` is run, it will not end up with an row in the `url_rewrite` table. It should.

![image](https://user-images.githubusercontent.com/1539397/49054298-a6cc3280-f1a8-11e8-94a5-a7175eea21d2.png)

After saving the product in Magento admin...
![image](https://user-images.githubusercontent.com/1539397/49054331-b8add580-f1a8-11e8-888a-61562a173663.png)

After running the command...
![image](https://user-images.githubusercontent.com/1539397/49054387-e7c44700-f1a8-11e8-86ac-44b9e24a5d04.png)

**Comment by joeldavuk** [comment]
I had a similar issue, categories and grouped products where fine but all simple products had no urls, this module worked https://github.com/elgentos/regenerate-catalog-urls

**Comment by olegkoval** [comment]
Hello @ctadlock , @joeldavuk 

I've released v1.4.0 and in this version you can select for what entity type you want to generate a URL rewrites (products or categories, see section "HOW TO").

So, if you want to generate a URL rewrites for products which are not assigned to any category then, please, use option "--entity-type=product".

Also, now you can specify a product ID (option "--product-id=111") or range of ID's (option "--products-range=101-152"). Same for categories.

Best regards,
Oleg Koval.
