### ISSUE TITLE
Not working for french store

### ISSUE THREAD

**Issue by rdesharnais** [olegkoval/magento2-regenerate_url_rewrites#64]
There seems to be a problem with rewriting urls for my french store.  English store (which uses the same urls as default) works fine, although it takes a very long time to complete (around 6 to 7 hours for all stores).  If I run for only store 2 (french) and monitor the url_rewrite table, I see your module is inserting and deleting urls in what seems to be a loop (inserting, deleting all, reinserting...).  And in the end the french urls don't work.

Thanks!

**Comment by olegkoval** [comment]
Hello @rdesharnais 

I've released v1.4.0. Please, test it and confirm that issue is fixed.

Best regards,
Oleg Koval.

**Comment by olegkoval** [comment]
Fixed in v1.4.2.
Closed.
