### ISSUE TITLE
Products Urls are not regenerated

### ISSUE THREAD

**Issue by ChintanKaneriya** [olegkoval/magento2-regenerate_url_rewrites#66]
I am using Magento 2.2.2

I have around 400 products in my website and these products are imported not created manually. It seems that all categories url working fine but products urls are not working.

I run below command:

` php bin/magento ok:urlrewrites:regenerate`

but still product urls are not regenerated and it returning urls like below:
`catalog/product/view/id/2/s/product-url/category/19/`

I also tried running other command as well:
`php bin/magento ok:urlrewrites:regenerate --save-old-urls`

Note I have `Use Categories Path for Product URLs` set to `Yes`.

But no luck. So, what is the real problem for this?

**Comment by olegkoval** [comment]
Hello @ChintanKaneriya 

From version 1.4.0 the default command (without params) regenerate only products URL rewrites (direct links to products). To regenerate a URL rewrites of products in some specific category (or in all categories), please, run commands:

- in all categories:
 `php bin/magento ok:urlrewrites:regenerate --entity-type=category`

- in specific category with ID=19 (category ID from your comment):
`php bin/magento ok:urlrewrites:regenerate --entity-type=category --category-id=19`

Best regards,
Oleg Koval
