### ISSUE TITLE
support for M2.3 and php7.2

### ISSUE THREAD

**Issue by n2diving-dgx** [olegkoval/magento2-regenerate_url_rewrites#67]
~/www/current$ **php bin/magento ok:urlrewrites:regenerate**
Regenerating of URL rewrites:

Please, support me on:
https://www.patreon.com/olegkoval
https://api.fondy.eu/s/ghYyR

[Store ID: 0, Store View code: admin]:
....
[Store ID: 1, Store View code: default]:
....

Reindexation...**PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)** in /home/iodev/www/releases/1546710204/vendor/magento/framework/Filesystem/Directory/Write.php on line 35
 Done
Cache refreshing...**PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)** in /home/iodev/www/releases/1546710204/vendor/magento/framework/Filesystem/Directory/Write.php on line 35
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/iodev/www/releases/1546710204/vendor/magento/framework/Filesystem/Directory/Write.php on line 35
 Done
If you use some external cache mechanisms (e.g.: Redis, Varnish, etc.) - please, refresh this external cache.

Please, support me on:
https://www.patreon.com/olegkoval
https://api.fondy.eu/s/ghYyR

Finished
~/www/current$ **php --version**
**PHP 7.2.12** (cli) (built: Nov 30 2018 12:51:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies

**Comment by olegkoval** [comment]
Hello @n2diving-dgx 
Thank you for the message.

This is the Magento core issue (not the extension). Please, check Magento issues report:
https://github.com/magento/magento2/issues/17285


Best regards,
Oleg Koval
