### ISSUE TITLE
[Enhancement] better separation of PRO features

### ISSUE THREAD

**Issue by simonrl** [olegkoval/magento2-regenerate_url_rewrites#68]
Hi,

it would actually be nice to have the PRO features better separated.

The `--help` does not say that features are not available in the open source version.

I just tried with the `--storeId` and `--product-id` parameter, and the result ist, that a full reindex takes place for the store - something I definitely did not want.

So, I'd suggest
- to remove the PRO parameters from the `--help` menu in the open source version
- and to throw an exception when a PRO parameter occurs, because the process gets stopped then and the user can think about his next action

Anyway, where can I buy the PRO version, and what is its license? Per shop / per agency...?

**Comment by olegkoval** [comment]
Hello @simonrl .
From v1.4.0 a "Pro" version of extension not exists and I've moved a key features into free version. So, now, regeneration of URL rewrites for specific product/category or for range of products/categories are available in free extension.
