### ISSUE TITLE
Segmentation fault on url rewrite

### ISSUE THREAD

**Issue by aglavas** [olegkoval/magento2-regenerate_url_rewrites#7]
I get Segmentation fault when running rewriter on one of my stores. 
Also there is nothing interesting in logs.
How to get past this problem?

**Comment by aglavas** [comment]
There is nothing interesting in Magento logs. Also there is nothing in apache error log.

Only thing I found is in kern.log, indications of that problem:

`[26568.490170] php[30116]: segfault at 7fff5e943ff8 ip 00007f08d8627bbc sp 00007fff5e943ff0 error 6 in libc-2.23.so[7f08d85a6000+1c0000]`

This log doesn't say much, except that there was segmentation fault, as we already know.

One thing to add, I edited your extension in RegenerateUrlRewrites.php after 169 line. 

Added output of whole exception to see whats going on, and that code wasn't even triggered.

Which points me to conclusion that failure doesn't come from code itself.

**Comment by olegkoval** [comment]
Hello.
Sorry for delay with answer.

This is not a extension or Magento issue - it's a php side.

Do you use a php-fpm and nginx?

**Comment by aglavas** [comment]
Hello,

it's ok. Any help is appreciated. Answer me when you have time.

No I don't. Would it help?

Are there any other fixes?

**Comment by lukepaoloni** [comment]
@olegkoval Is correct. It's usually to do with the version of PHP running on your server. Try `/usr/local/bin/ea-php70 bin/magento`. Notice that the version of PHP is 7.0.

**Comment by olegkoval** [comment]
Closed.
Is not related to extension code.
