### ISSUE TITLE
v1.4.0 is not on packagist.org

### ISSUE THREAD

**Issue by bjoern-flagbit** [olegkoval/magento2-regenerate_url_rewrites#70]
Hey @olegkoval, if you have time can you update the module on packagist.org? Because at the moment the latest version there is 1.3.1. But maybe I'm just a bit early here. Thx for your work. 👍

**Comment by olegkoval** [comment]
Hello @bjoern-flagbit 

Thank you for report.

Just updated on packagist (I don't know why GitHub hook not fired).

Best regards,
Oleg Koval
