### ISSUE TITLE
Check product use categories configuration

### ISSUE THREAD

**Issue by bjoern-flagbit** [olegkoval/magento2-regenerate_url_rewrites#71]
Just a suggestion ... you should check if this is set to true:
`groups[seo][fields][product_use_categories][value]`

And if this is not set to true you can just skip this part.

_Console/Command/RegenerateUrlRewritesCategoryAbstract.php_
```
$productUrlRewriteResult = $this->_getUrlRewriteHandler()->generateProductUrlRewrites($category);

// fix for double slashes issue
foreach ($productUrlRewriteResult as &$urlRewrite) {
  $urlRewrite->setRequestPath($this->_clearRequestPath($urlRewrite->getRequestPath()));
}

$this->_doBunchReplaceUrlRewrites($productUrlRewriteResult, 'Product');
```

What do you think?

**Comment by olegkoval** [comment]
@bjoern-flagbit @scolandrea 
Hi.

Maybe create a option for this and if command was executed with this option then script will take into account this config value and skip/not skip this part of logic?

Because for main part of store owners this will not be clear. But who knows can use the option.

**Comment by scolandrea** [comment]
@olegkoval Hi!

Yeah, definitely this functionality should be optional because by default Magento uses _ product_use_categories_ only when it was set as true.

It might be an optional argument for the regenerate command.

What do you think?

**Comment by werfu** [comment]
I would go with @bjoern-flagbit suggestion,  as the URL generated of new product later on would be the same as those regenerated. It force store owner to be consistent with their store config. BUT, it should be documented.

**Comment by olegkoval** [comment]
Hello @bjoern-flagbit , @scolandrea .

Please, upgrade to v1.4.2. I've added this option and name of option is "--check-use-category-in-product-url".

Best regards,
Oleg Koval
