### ISSUE TITLE
Save URL Key

### ISSUE THREAD

**Issue by ArthurSCD** [olegkoval/magento2-regenerate_url_rewrites#76]
Hello,

Is this no longer an option ? `--no-clean-url-key`

It seemed pretty useful in M1 to M2 conversions.

Thanks.

**Comment by olegkoval** [comment]
Hello @ArthurSCD 

If this option is a useful then I will add it back in version 1.4.2 (plan to release in this weekend).
The option was added in latest v1.3.x branch and in same time v1.4 was in development and did not included this option.

**Comment by ArthurSCD** [comment]
Yeah, I've been doing M1>M2 conversions and it's quite helpful over getting things to generate with base M2. Thanks for the great module.

**Comment by ArthurSCD** [comment]
Re-opened since it seems url-key wasn't re-added in 1.4.2. Immensely useful honestly.

**Comment by olegkoval** [comment]
Hello All.

This option is come back but with new name (it have 2 functions now: not clean URL key and not regenerate new URL key): '--no-regen-url-key' .

Best regards,
Oleg
