### ISSUE TITLE
Generating the url with extra dots and slash?

### ISSUE THREAD

**Issue by Adel-Magebinary** [olegkoval/magento2-regenerate_url_rewrites#79]
somehow generating URL like below:

brands.//anatom-q5-aonach-mountain-boots.html

**Comment by Adel-Magebinary** [comment]
or this

brands/earth-sea-sky./earth-sea-sky-women-s-plume-pullover.html

**Comment by olegkoval** [comment]
Hello @Adel-Magebinary 

Please, upgrade extension to v1.4.2 - this issue should be fixed. Please confirm.

Best regards,
Oleg Koval

**Comment by olegkoval** [comment]
Fixed in v1.4.2

**Comment by Adel-Magebinary** [comment]
Hello Oleg,

Thanks for releasing the fix but your logic has a bit of an error. Since it is indexing by category name not category url_key. Sometimes, the merchant makes custom-url for their category urls. 

There are currently two issues.

``
                $productUrlRewriteResult = $this->_getUrlRewriteHandler()->generateProductUrlRewrites($category);

                // fix for double slashes issue and dots
                foreach ($productUrlRewriteResult as &$urlRewrite) {
                    $urlRewrite->setRequestPath($this->_clearRequestPath($urlRewrite->getRequestPath()));
                }

                $this->_doBunchReplaceUrlRewrites($productUrlRewriteResult, 'Product');

Above line is very slow method to generate the url keys.


``
    protected function _categoryProcess($category, $storeId = 0)
    {
        try {
            if ($this->_commandOptions['saveOldUrls']) {
                $category->setData('save_rewrites_history', true);
            }

            $category->setStoreId($storeId);
            // you are currently passing the name and I have changed your code into below line. However, it brings back the broken url issue. eg, ./ ../ ..html etc. Please use getUrlKey instead of getName().
            **$category->setUrlKey($this->_clearRequestPath($category->getUrlKey()));**
            $category->getResource()->saveAttribute($category, 'url_key');
            $category->setUrlPath($this->_clearRequestPath($this->_categoryUrlPathGenerator->getUrlPath($category)));
            $category->getResource()->saveAttribute($category, 'url_path');

            $this->_regenerateCategoryUrlRewrites($category, $storeId);

            //frees memory for maps that are self-initialized in multiple classes that were called by the generators
            $this->_resetUrlRewritesDataMaps($category);

            $this->_progress++;
            $this->_displayProgressBar();
        } catch (\Exception $e) {
            // debugging
            $this->_addConsoleMsg('Exception: '. $e->getMessage() .' Category ID: '. $category->getId());
        }
    }


I was going to send you a pull request but we have a couple of projects atm that I need to chase the timeline. 

Let me know if you have any questions for above.

Cheers,
Adel
