### ISSUE TITLE
Area Code Not Set After Installing Module On 2.3

### ISSUE THREAD

**Issue by davoc** [olegkoval/magento2-regenerate_url_rewrites#80]
After installing the module into an existing Magento 2.3 site I am getting the error "Area code not set" when trying to load any page, frontend or backend. Disabling the module removes this error from the store.

**Comment by olegkoval** [comment]
Hello @davoc 

Can you provide this information:
- which version of extension you use?
- how you installed an extension? composer, manually , ...?

Thank you.

Best regards,
Oleg Koval.

**Comment by olegkoval** [comment]
Not actual. Closed.
