### ISSUE TITLE
Instead of saving url_path of products to NULL, it should get deleted

### ISSUE THREAD

**Issue by hostep** [olegkoval/magento2-regenerate_url_rewrites#90]
Hi!

First time trying this module, I'm trying to understand what it does, so I'm comparing database tables before and after running this module to see what it actually changes.

I've noticed that after running this tool, it inserts a whole bunch of `NULL` values for the `url_path` attribute for products. I understand why you do this, and it seems to happen [here](https://github.com/olegkoval/magento2-regenerate_url_rewrites/blob/master/Console/Command/RegenerateUrlRewritesProductAbstract.php#L85-L89). But I think it would be better to remove existing values, instead of storing a new value when one wasn't set before.
Magento also doesn't create a `url_path` value for a product when manually saving products so I think this tool should try to mimic that.

This is not a big deal though, just thought I should mention it.

Thanks for the effort put into this so far! :)

**Comment by olegkoval** [comment]
Hello @hostep.

From starting from version 1.5.0 it delete rewrites instead of set NULL. Please, update extension.

Closed.

Best regards,
Oleg Koval
