### ISSUE TITLE
Shouldn't change url_key's if they are already defined

### ISSUE THREAD

**Issue by hostep** [olegkoval/magento2-regenerate_url_rewrites#93]
Hi!

For some reason this tool changes existing url_keys on products. Why does this happen? If it is already defined, it shouldn't overwrite it with a newly generated one? Shop owners want to have control over the url keys, the tool shouldn't assume that it can blindly overwrite these values I think.

It would be appreciated if some option can be added to stop this from happening (or even make this the default behaviour, since I don't think people are expecting this?).

But it should still generate url_key's for products when they don't have one yet.

Thanks!

**Comment by werfu** [comment]
As explained in #78 , this is default behavior. My PR was refused for this reason. However, I will submit soon a PR with the reverse option, that is not to regen URL_key.

**Comment by werfu** [comment]
See #94 if you want to test.

**Comment by olegkoval** [comment]
Pull request was accepted. Option was added in release [v1.4.3](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.4.3)

Please confirm to close a ticket.

**Comment by hostep** [comment]
Thanks @olegkoval & @werfu!

This new option says to not generate url_key's at all, which is already a very nice improvement!
Just briefly tested it and it seems to works like was intended.
But it's not fully fixing this issue I think.

I would like to see a behavior in this tool where it corrects incorrect url_key's (meaning: missing/empty ones), but it shouldn't touch the ones which are already filled in.

In that case, it will make sure all products have an url_key in the database on every storeview and it would also not overwrite those which got manually entered.

Is this something which makes sense?

Thanks!

**Comment by olegkoval** [comment]
Implemented. Closed.

**Comment by tuyennn** [comment]
Have same problem as @hostep defined, that means the module generated **all store views** url_key even the entity was marked as **Use Default**.

Unfortunately the problem is still exist.
