### ISSUE TITLE
error on composer install

### ISSUE THREAD

**Issue by ccrothers** [olegkoval/magento2-regenerate_url_rewrites#95]
PHP Fatal error:  strict_types declaration must be the very first statement in the script in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(193) : eval()'d code on line 6
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/composer:0
PHP   2. require() /usr/local/bin/composer:24
PHP   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
PHP   4. Composer\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:101
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
PHP   6. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:221
PHP   7. Composer\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
PHP   8. Composer\Command\RequireCommand->run() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
PHP   9. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
PHP  10. Composer\Command\RequireCommand->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:146
PHP  11. Composer\Console\Application->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php:53
PHP  12. Composer\Factory::create() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:299
PHP  13. Composer\Factory->createComposer() phar:///usr/local/bin/composer/src/Composer/Factory.php:552
PHP  14. Composer\Plugin\PluginManager->loadInstalledPlugins() phar:///usr/local/bin/composer/src/Composer/Factory.php:361
PHP  15. Composer\Plugin\PluginManager->loadRepository() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:76
PHP  16. Composer\Plugin\PluginManager->registerPackage() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:255

Fatal error: strict_types declaration must be the very first statement in the script in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(193) : eval()'d code on line 6

Call Stack:
    0.0010     352088   1. {main}() /usr/local/bin/composer:0
    0.0086     563528   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:24
    0.0499    3044872   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
    0.0518    3278592   4. Composer\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:101
    0.0525    3348176   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
    0.6119    9963464   6. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:221
    0.6120    9963464   7. Composer\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
    0.6120    9963464   8. Composer\Command\RequireCommand->run() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
    0.6124    9966720   9. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
   16.0727  219514920  10. Composer\Command\RequireCommand->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:146
   16.0727  219514920  11. Composer\Console\Application->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php:53
   16.0727  219514920  12. Composer\Factory::create() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:299
   16.0727  219514960  13. Composer\Factory->createComposer() phar:///usr/local/bin/composer/src/Composer/Factory.php:552
   16.0992  219568296  14. Composer\Plugin\PluginManager->loadInstalledPlugins() phar:///usr/local/bin/composer/src/Composer/Factory.php:361
   16.0992  219568296  15. Composer\Plugin\PluginManager->loadRepository() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:76
   16.2043  222400680  16. Composer\Plugin\PluginManager->registerPackage() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:255

**Comment by hostep** [comment]
@ccrothers: hmm, this codebase doesn't use `strict_types` anywhere. And I also only see composer source code in your stracktrace. Are you sure this is caused by this `magento2-regenerate_url_rewrites` module? I'd expect it to be a bug in composer itself, maybe try updating it to a more recent version?
I had no problems installing this module recently using composer version 1.8.0.

**Comment by ccrothers** [comment]
Module worked famously when installed manually. Not sure why composer had issues. May be a version issue. I can provide my composer version Monday. I'm also running Magento EE 2.3 so that may also play a role. I had no problems running composer install to populate the whole vendor directory.

Beyond that bump in the road tho, seriously great module! Very handy!
