### ISSUE TITLE
Typo in _getLogicalConflictError

### ISSUE THREAD

**Issue by chelevich** [olegkoval/magento2-regenerate_url_rewrites#96]
https://github.com/olegkoval/magento2-regenerate_url_rewrites/blob/38bec7a0a3d6695b098b8df0239f974158206ca4/Console/Command/RegenerateUrlRewrites.php#L352

Message format requires `%o3`, array has key `o4`

**Comment by olegkoval** [comment]
Thank you for the report. Fixed in commit https://github.com/olegkoval/magento2-regenerate_url_rewrites/commit/c5649694c32c2d9a8eda462a3e962a0dc1573277
