### ISSUE TITLE
Getting an error after installation

### ISSUE THREAD

**Issue by l0stb0y** [olegkoval/magento2-regenerate_url_rewrites#97]
When attempting to run the command I get 'There are no commands defined in the "ok:urlrewrites" namespace."

The code files are in place. Everything looks ok

Any ideas?

Thanks,

bastien

**Comment by olegkoval** [comment]
Hello @l0stb0y 

Looks like you did not finished a installation process or maybe you just copied a code but extension is not "registered" in Magento. Can you describe how you installed it (installation process)?

Best regards,
Oleg

**Comment by l0stb0y** [comment]
I copied the code into the folder /app/code/OlegKoval/RegenerateUrlRewrites and then ran the upgrade command. It seems to work and shows the module in the list, but when I run the command for the url rewrite, I get the error message
![Screen Shot 2019-05-10 at 9 53 36 AM](https://user-images.githubusercontent.com/1054677/57532491-c778e680-7309-11e9-8438-e5355b1e396b.png)

**Comment by olegkoval** [comment]
Hi Bastien.

Can we make a call with screensharing (from your side)? Because it's a strange that you have this error when extension is installed properly.

Best regards,
Oleg.

**Comment by RIKIPB** [comment]
Hi! I have the same error, how I can resolve it?

**Comment by olegkoval** [comment]
Hello @l0stb0y 
Can you, please, add here a complete list of enabled extensions in your Magento installation? Because on the screenshot I do not see a extension "OlegKoval_RegenerateUrlRewrites".

Hello @RIKIPB 
Can you, please, also add here the list of extension which are installed and enables in your Magento installation?

Thank you.

Best regards,
Oleg Koval

**Comment by RIKIPB** [comment]
This is the list:
`List of enabled modules:
Magento_Store
Magento_Directory
Magento_Theme
Magento_Variable
Cadence_UrlDedup
Magento_Backend
Emipro_Reviewnotification
Magento_Eav
Magento_AdminNotification
Magento_Indexer
Magento_Customer
MSP_ReCaptcha
Magento_Config
Magento_Cms
Magento_Email
Magento_Quote
Magento_AdvancedPricingImportExport
Magento_Search
Magento_Amqp
Magento_Security
Magento_User
Magento_Authorization
Magento_Rule
Magento_Catalog
Magento_Backup
Magento_SalesSequence
Magento_Bundle
Magento_GraphQl
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_Payment
Magento_CatalogInventory
Magento_Integration
Magento_EavGraphQl
Magento_CatalogImportExport
Magento_Sales
Magento_CatalogInventoryGraphQl
Magento_Cron
Magento_Msrp
Magento_CatalogRule
Magento_CatalogUrlRewrite
Magento_CatalogUrlRewriteGraphQl
Magento_Widget
Magento_Checkout
Magento_CheckoutAgreements
Magento_Vault
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
MSP_TwoFactorAuth
Magento_ConfigurableImportExport
Magento_ConfigurableProduct
Magento_StoreGraphQl
Magento_ConfigurableProductSales
Magento_Contact
Magento_Cookie
Magento_Newsletter
Magento_CurrencySymbol
Magento_Paypal
Magento_Analytics
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_DataMigrationTool
Magento_Deploy
Magento_Developer
Magento_Dhl
Ibnab_CategoriesSide
Magento_Downloadable
Magento_CatalogGraphQl
Magento_ImportExport
Klarna_Core
Magento_BundleGraphQl
Magento_AdvancedSearch
MagePal_GmailSmtpApp
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_ConfigurableProductGraphQl
Magento_GroupedImportExport
Magento_GroupedProduct
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Amazon_Core
Magento_InstantPurchase
Magento_CatalogAnalytics
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_CatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryIndexer
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryReservations
Magento_InventoryReservationsApi
Magento_InventoryCache
Magento_InventorySalesAdminUi
Magento_InventorySalesApi
Magento_InventorySalesFrontendUi
Magento_InventoryShipping
Magento_Shipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_Multishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_ProductAlert
Magento_OfflinePayments
Magento_SalesRule
Magento_PageCache
MagePal_CustomShippingRate
Magento_Braintree
Magento_Persistent
Magento_Reports
Magento_ProductVideo
Magento_Authorizenet
Magento_QuoteAnalytics
Magento_QuoteGraphQl
Magento_ReleaseNotification
Magento_Review
Magento_RequireJs
Magento_SendFriend
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Klarna_Ordermanagement
Magento_Captcha
Magento_SalesAnalytics
Magento_SalesInventory
Magento_OfflineShipping
Amazon_Login
Magento_UrlRewrite
Magento_Elasticsearch
Magento_CustomerAnalytics
Magento_Wishlist
Magento_InventoryShippingAdminUi
Magento_Signifyd
Magento_Sitemap
Amazon_Payment
Magento_DownloadableGraphQl
Magento_Webapi
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_Tinymce3
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_UrlRewriteGraphQl
Magento_AsynchronousOperations
Magento_Usps
Magento_InventoryCatalogSearch
Klarna_Kp
Magento_Version
Magento_Swagger
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_Weee
Magento_WeeeGraphQl
Magento_CatalogWidget
Dotdigitalgroup_Email
Magento_WishlistAnalytics
Mageplaza_Core
Mageplaza_BannerSlider
Meetanshi_PaymentSurcharge
Ncd_Customleftnav
Ncd_Customtopmenu
OlegKoval_RegenerateUrlRewrites
Tatvic_EnhancedEcommerce
Temando_Shipping
Trustpilot_Reviews
Vertex_Tax
WaPoNe_Stickers
WebShopApps_MatrixRate
Webgriffe_UnicreditImprese

List of disabled modules:
Appmerce_Sofort
Mageplaza_Seo
Mageplaza_Sitemap
Scandi_MagicZoom
`

**Comment by olegkoval** [comment]
Hello @RIKIPB 

Yes, I see that extension is enabled. And you still have error 'There are no commands defined in the "ok:urlrewrites" namespace.'? Can you provide me access to your Magento installation or maybe you have a sandbox/test server and we can use it to debug this issue?

You can contact me via email.

Best regards,
Oleg Koval

**Comment by RIKIPB** [comment]
@olegkoval Thank you so much for your assistance, everything seems to be working properly now!

**Comment by olegkoval** [comment]
Fixed. Closed.

**Comment by pattu310** [comment]
I have Same Error Can I know Reason ?

**Comment by olegkoval** [comment]
Hello @pattu310 

Can you provide me access to your server (like RIKIPB)? So, I can debug this.

**Comment by pattu310** [comment]
RIKIPB means ?

**Comment by pattu310** [comment]
Give me Your Mail Id.

**Comment by olegkoval** [comment]
@pattu310  contact [at] olegkoval.com

**Comment by koopjesboom** [comment]
Best,

If installed with composer: **composer require olegkoval/magento2-regenerate-url-rewrites**

The:  **OlegKoval_RegenerateUrlRewrites** Or whatever it needs to be vendor_extensionname **Is not in the config.php file**.
Seems the config.php file is not update during installation.

Error: **There are no commands defined in the "ok:urlrewrites" namespace.**
Because the module is not registered during installation.

What is the correct vendor_extensionname?

Please cab you verify?
Can you provide me a solution for this?.

Best regards

**Comment by teodorpav** [comment]
> Fixed. Closed.

I have the same error.
How to fix it?

**Comment by Green2Matter** [comment]
My case is exactly the same: module was installed without errors, enabled and listed on module list. What needs to be done to get your module working?
