### ISSUE TITLE
fix duplicate on the fly

### ISSUE THREAD

**Issue by psol7** [olegkoval/magento2-regenerate_url_rewrites#98]
Is there  a way to add a number in the url key at generations to fix on the fly duplicates?

**Comment by lamasfoker** [comment]
In my opinion I think that is more useful modify the url_key appending a number on it, as @psol7 said.

**Comment by olegkoval** [comment]
Hello.

This logic was implemented in version 1.5.0. Please update extension.

Best regards,
Oleg Koval.
